### PR TITLE
Adding ImageParameters struct to represent height, width, quality and…

### LINKED ISSUE #6: Use a struct instead of uint, uint, uint in parser.go
Might be easier to understand what each value is, as well as easier to extend (if needed).

@astagi if you're ok with this, I can take it on later today.

### PR DESCRIPTION
**Pull request by peterj**
… updating the rest of the code to use it. Fixes #6

### CODE REVIEW

**Comment by Remeic** [comment]
Hi @peterj, sorry but we can't merge this PR, first motivation we use 4 space instead of tab for formatting our code and second motivation is because this PR don't pass tests, see this

`# _/run/media/giulio/Lavoro/lotrek/piuma/core_test
core/parser_test.go:16: undefined: core.ImageParameters
core/parser_test.go:55: assignment count mismatch: 2 = 4
`
`# _/run/media/giulio/Lavoro/lotrek/piuma
./server.go:24: assignment count mismatch: 2 = 4
./server.go:26: not enough arguments in call to core.Optimize
	have (string, <T>, string, string)
	want (string, uint, uint, uint, string, string)
`

**Review by Remeic — CHANGES_REQUESTED** [review]
Indentation with 4 space and fix for pass tests

**Comment by peterj** [comment]
Odd that the tests are failing - if you look at the ```optimizer.go``` you should see that I did update the func to take the new ```imageParameters``` struct.

I fixed the spaces though in all files - I missed the requirement in README or somewhere - by default golang uses tabs :)

**Review by Remeic — APPROVED** [review]

**Comment by Remeic** [comment]
@peterj Sorry for inconvenience, my mistake thanks again @peterj

**Comment by peterj** [comment]
No worries! At least the CircleCI is in now, so it ran the tests.

**Pull request merged**
